#include "FirstEngine/Core/ConfigFile.h"
#include <iostream>
#include <algorithm>
#include <cctype>
#include <vector>

namespace FirstEngine {
    namespace Core {

        bool ConfigFile::LoadFromFile(const std::string& filepath) {
            m_Values.clear();

            std::ifstream file(filepath);
            if (!file.is_open()) {
                std::cerr << "ConfigFile: Failed to open file: " << filepath << std::endl;
                return false;
            }

            std::string line;
            while (std::getline(file, line)) {
                // Remove comments (everything after # or ;)
                size_t commentPos = line.find('#');
                if (commentPos != std::string::npos) {
                    line = line.substr(0, commentPos);
                }
                commentPos = line.find(';');
                if (commentPos != std::string::npos) {
                    line = line.substr(0, commentPos);
                }

                // Trim whitespace
                line = Trim(line);

                // Skip empty lines
                if (line.empty()) {
                    continue;
                }

                // Parse key=value
                size_t equalPos = line.find('=');
                if (equalPos != std::string::npos) {
                    std::string key = Trim(line.substr(0, equalPos));
                    std::string value = Trim(line.substr(equalPos + 1));
                    if (!key.empty()) {
                        m_Values[key] = value;
                    }
                }
            }

            file.close();
            return true;
        }

        bool ConfigFile::SaveToFile(const std::string& filepath) const {
            std::ofstream file(filepath);
            if (!file.is_open()) {
                std::cerr << "ConfigFile: Failed to create file: " << filepath << std::endl;
                return false;
            }

            // Write header comment
            file << "# FirstEngine Configuration File\n";
            file << "# This file is automatically generated. Do not edit manually.\n\n";

            // Write all key-value pairs
            for (const auto& pair : m_Values) {
                file << pair.first << "=" << pair.second << "\n";
            }

            file.close();
            return true;
        }

        std::string ConfigFile::GetValue(const std::string& key, const std::string& defaultValue) const {
            auto it = m_Values.find(key);
            if (it != m_Values.end()) {
                return it->second;
            }
            return defaultValue;
        }

        void ConfigFile::SetValue(const std::string& key, const std::string& value) {
            m_Values[key] = value;
        }

        bool ConfigFile::HasKey(const std::string& key) const {
            return m_Values.find(key) != m_Values.end();
        }

        std::vector<std::string> ConfigFile::GetKeys() const {
            std::vector<std::string> keys;
            keys.reserve(m_Values.size());
            for (const auto& pair : m_Values) {
                keys.push_back(pair.first);
            }
            return keys;
        }

        void ConfigFile::Clear() {
            m_Values.clear();
        }

        std::string ConfigFile::Trim(const std::string& str) {
            if (str.empty()) {
                return str;
            }

            size_t start = 0;
            while (start < str.length() && std::isspace(static_cast<unsigned char>(str[start]))) {
                start++;
            }

            if (start >= str.length()) {
                return "";
            }

            size_t end = str.length() - 1;
            while (end > start && std::isspace(static_cast<unsigned char>(str[end]))) {
                end--;
            }

            return str.substr(start, end - start + 1);
        }

    } // namespace Core
} // namespace FirstEngine
